apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jukefy-3scale-subscription
  # namespace: openshift-operators 
spec:
  channel: threescale-2.11
  name: 3scale-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace 