#SCRIPTS
$npm_install = <<-SCRIPT
sudo dnf update &&
sudo dnf install -y npm &&
sudo npm install -g expo-cli
SCRIPT


# Master vars
Vagrant.configure("2") do |config|
  # Box de Ansible (master)
  config.vm.define 'master' do |master|
    master.vm.box = "generic/centos8"
    master.vm.synced_folder ".", "/vagrant"
    master.vm.provider "virtualbox" do |v|
      v.memory = 4096
    end

    master.vm.hostname = 'jukebox-dev-env'

    master.vm.provision "shell", inline: $npm_install
  end
end